name: Deploy emails
on:
  repository_dispatch:
    types: rebuild
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: npm install
      run: npm i
    
    - name: npm run-script build
      run: npm run-script build
    
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ".output/*"
        token: ${{ secrets.GITHUB_TOKEN }}